apiVersion: v1
kind: Pod
metadata:
    name: redis-pod-new
spec:
    containers:
        - image: redis
          name: redisdb
          volumeMounts:
            - name: redis-data
              mountPath: /data
          ports: 
            - containerPort: 6379
              protocol: TCP
    volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-volume-claim