apiVersion: v1
kind: PersistentVolume
metadata: 
    name: redis-pv
spec:
    storageClassName: ""
    capacity:
        storage: 10G
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/redis